version: '3.3'

services:
  mysql:
    image: mysql:5.5
    ports:
    - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-my-secret-pw}
  redis:
    image: redis:latest
    ports:
    - "${REDIS_PORT:-6379}:6379"
  api:
    depends_on: 
      - mysql
      - redis
    build: 
      context: "./"
      dockerfile: src/YS.ShortLink.App/Dockerfile
    ports:
      - "${API_PORT:-80}:80"
    volumes:
      - ./scripts:/scripts
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Redis__ConnectionString: redis:6379
      ConnectionStrings__SequenceContext: Server=mysql;Port=3306;Database=SequenceContext; User=root;Password=my-secret-pw;
    entrypoint: sh -c "/scripts/wait-for-it.sh mysql:3306 -- dotnet YS.ShortLink.App.dll Knife:Stage=install && dotnet YS.ShortLink.App.dll"